# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- script: |
    echo **********************************************************************************************
    echo               Build is about Start ..........
    echo **********************************************************************************************
  displayName: 'FirsitMessage'
- script: |
    echo **********************************************************************************************
    echo              Copying Files into the Build  ..........
    echo **********************************************************************************************
  displayName: 'SecondMessage'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'
- script: |
    echo **********************************************************************************************
    echo              Copy File Completed !!!
    echo **********************************************************************************************
  displayName: 'ThirdMessage'
- script: |
    echo **********************************************************************************************
    echo              Publishing File to Artifact  !!!
    echo **********************************************************************************************
  displayName: 'FourthMessage'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- script: |
    echo **********************************************************************************************
    echo              Files Droped Into Artifcats !!!
    echo **********************************************************************************************
  displayName: 'FifthMessage'